_target_: pytorch_lightning.Trainer

min_epochs: 200
max_epochs: 300
check_val_every_n_epoch: 10

resume_from_checkpoint: null

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
